object FormDockHost: TFormDockHost
  Left = 0
  Top = 0
  ClientHeight = 202
  ClientWidth = 304
  Color = clWindow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 13
  object spl_DockLeft: TSplitter
    Left = 48
    Top = 0
    Width = 4
    Height = 202
    AutoSnap = False
    ResizeStyle = rsUpdate
    Visible = False
    OnMoved = DockSplitterMoved
    ExplicitLeft = 20
    ExplicitTop = -2
    ExplicitHeight = 336
  end
  object spl_DockRight: TSplitter
    Left = 252
    Top = 0
    Width = 4
    Height = 202
    Align = alRight
    AutoSnap = False
    ResizeStyle = rsUpdate
    Visible = False
    OnMoved = DockSplitterMoved
    ExplicitLeft = 578
    ExplicitTop = -123
    ExplicitHeight = 473
  end
  object pnl_DockLeft: TPanel
    Left = 24
    Top = 0
    Width = 24
    Height = 202
    Align = alLeft
    BevelOuter = bvNone
    DockSite = True
    TabOrder = 0
    OnDockDrop = DockPanelDockDrop
    OnDockOver = DockPanelDockOverLeft
    OnGetSiteInfo = DockPanelGetSiteInfo
    OnUnDock = DockPanelUnDock
  end
  object dts_DockTabSetLeft: TDockTabSet
    Left = 0
    Top = 0
    Width = 24
    Height = 202
    Align = alLeft
    DoubleBuffered = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentDoubleBuffered = False
    ShrinkToFit = True
    Style = tsModernTabs
    TabPosition = tpLeft
    Visible = False
    AutoSelect = True
    DestinationDockSite = pnl_DockLeft
    OnDockDrop = DockTabSetDockDrop
    OnGetSiteInfo = DockTabSetGetSiteInfoLeft
    OnUnDock = DockTabSetUnDock
    OnTabAdded = DockTabSetTabAdded
    OnTabRemoved = DockTabSetTabRemoved
  end
  object pnl_DockRight: TPanel
    Left = 256
    Top = 0
    Width = 24
    Height = 202
    Align = alRight
    BevelOuter = bvNone
    DockSite = True
    TabOrder = 1
    OnDockDrop = DockPanelDockDrop
    OnDockOver = DockPanelDockOverRight
    OnGetSiteInfo = DockPanelGetSiteInfo
    OnUnDock = DockPanelUnDock
  end
  object dts_DockTabSheetRight: TDockTabSet
    Left = 280
    Top = 0
    Width = 24
    Height = 202
    Align = alRight
    DoubleBuffered = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentDoubleBuffered = False
    ShrinkToFit = True
    Style = tsModernTabs
    TabPosition = tpRight
    Visible = False
    AutoSelect = True
    DestinationDockSite = pnl_DockRight
    OnDockDrop = DockTabSetDockDrop
    OnGetSiteInfo = DockTabSetGetSiteInfoRight
    OnUnDock = DockTabSetUnDock
    OnTabAdded = DockTabSetTabAdded
    OnTabRemoved = DockTabSetTabRemoved
  end
  object pnl_Main: TPanel
    Left = 52
    Top = 0
    Width = 200
    Height = 202
    Align = alClient
    BevelOuter = bvNone
    ParentBackground = False
    TabOrder = 4
    object spl_DockBottom: TSplitter
      Left = 0
      Top = 150
      Width = 200
      Height = 4
      Cursor = crVSplit
      Align = alBottom
      AutoSnap = False
      ResizeStyle = rsUpdate
      Visible = False
      OnMoved = DockSplitterMoved
      ExplicitTop = 144
    end
    object dts_DockTabSetBottom: TDockTabSet
      Left = 0
      Top = 178
      Width = 200
      Height = 24
      Align = alBottom
      DoubleBuffered = True
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = True
      ParentDoubleBuffered = False
      SoftTop = True
      Style = tsModernTabs
      Visible = False
      AutoSelect = True
      DestinationDockSite = pnl_DockBottom
      OnDockDrop = DockTabSetDockDrop
      OnGetSiteInfo = DockTabSetGetSiteInfoBottom
      OnUnDock = DockTabSetUnDock
      OnTabAdded = DockTabSetTabAdded
      OnTabRemoved = DockTabSetTabRemoved
    end
    object pnl_DockBottom: TPanel
      Left = 0
      Top = 154
      Width = 200
      Height = 24
      Align = alBottom
      BevelOuter = bvNone
      Color = clWindow
      DockSite = True
      ParentBackground = False
      TabOrder = 1
      OnDockDrop = DockPanelDockDrop
      OnDockOver = DockPanelDockOverBottom
      OnGetSiteInfo = DockPanelGetSiteInfo
      OnUnDock = DockPanelUnDock
    end
  end
end
