object FormDockableBase: TFormDockableBase
  Left = 565
  Top = 626
  BorderStyle = bsSizeToolWin
  ClientHeight = 222
  ClientWidth = 296
  Color = clWindow
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  OnClose = FormClose
  OnEndDock = FormEndDock
  OnShow = FormShow
  OnStartDock = FormStartDock
  PixelsPerInch = 96
  TextHeight = 13
end
