object FormDockHostJoin: TFormDockHostJoin
  Left = 565
  Top = 626
  BorderStyle = bsSizeToolWin
  Caption = 'DackHostJoin'
  ClientHeight = 222
  ClientWidth = 296
  Color = clBtnFace
  UseDockManager = True
  DockSite = True
  DoubleBuffered = True
  DragKind = dkDock
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  OnClose = FormClose
  OnDockDrop = ControlDockDrop
  OnDockOver = ControlDockOver
  OnGetSiteInfo = ControlGetSiteInfo
  OnShow = FormShow
  OnUnDock = ControlUnDock
  PixelsPerInch = 96
  TextHeight = 13
end
